version: '3.8'
services:
  rest-api:
    container_name: warehouse-rest-api
    restart: on-failure
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - .:/usr/src/app
      - 'node_modules:/app/node_modules'
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
volumes:
  node_modules: null
